<?php
/**
 * Content Engine: Bulk-generates Hindu SEO blog posts using Gemini AI.
 *
 * Generates three types of content:
 *   1. Hindu Calendar — 12 months × 3 countries × 9 languages (324 posts)
 *   2. Pooja Guides   — 20 poojas × 9 languages (180 posts)
 *   3. Slokas & Mantras — 10 deity collections × 9 languages (90 posts)
 *
 * Each post is displayed as an interactive flipbook (StPageFlip.js).
 * Content is generated by Gemini 2.0 Flash; featured images by Imagen 4.0 Fast.
 * Posts are FREE / public — optimised for SEO.
 *
 * Called exclusively from AJAX handlers in SAS_Admin.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class SAS_Content_Engine {

    // ── Content-type identifiers (stored in sas_content_type post meta) ──

    const TYPE_CALENDAR = 'hindu_calendar';
    const TYPE_POOJA    = 'pooja_guide';
    const TYPE_SLOKA    = 'sloka_collection';

    // ── Language map (code → display name for Gemini prompts) ─────────────

    const LANG_NAMES = [
        'en' => 'English',
        'hi' => 'Hindi',
        'ta' => 'Tamil',
        'te' => 'Telugu',
        'ka' => 'Kannada',
        'ml' => 'Malayalam',
        'be' => 'Bengali',
        'sp' => 'Spanish',
        'fr' => 'French',
    ];

    // ── Countries and their timezone descriptions ──────────────────────────

    const COUNTRIES = [
        'India' => 'IST (UTC+5:30)',
        'UK'    => 'GMT/BST (UTC+0/+1)',
        'USA'   => 'EST/PST (UTC-5/-8)',
    ];

    // ── 20 most popular poojas ─────────────────────────────────────────────

    const POOJAS = [
        'Ganesh Puja',            'Lakshmi Puja',
        'Saraswati Puja',         'Shiva Puja',
        'Durga Puja',             'Hanuman Puja',
        'Satyanarayan Puja',      'Navgraha Puja',
        'Kali Puja',              'Krishna Janmashtami Puja',
        'Ram Navami Puja',        'Navratri Puja',
        'Diwali Lakshmi Puja',    'Holika Dahan Puja',
        'Chhath Puja',            'Karva Chauth Puja',
        'Vastu Puja',             'Griha Pravesh Puja',
        'Vivah Puja',             'Annaprashan Puja',
    ];

    // ── 10 deity sloka collections ─────────────────────────────────────────

    const SLOKA_DEITIES = [
        'Ganesha', 'Lakshmi', 'Saraswati', 'Shiva', 'Vishnu',
        'Hanuman', 'Durga',   'Rama',      'Krishna', 'Surya',
    ];

    // ── Months ────────────────────────────────────────────────────────────

    const MONTHS = [
        'January', 'February', 'March',     'April',
        'May',     'June',     'July',      'August',
        'September','October', 'November',  'December',
    ];

    // ── Boot ─────────────────────────────────────────────────────────────

    public static function init(): void {
        // Enqueue flipbook assets on single posts created by the Content Engine
        add_action( 'wp_enqueue_scripts', [ __CLASS__, 'maybe_enqueue_flipbook' ] );

        // Wrap post content in flipbook container + add share bar
        add_filter( 'the_content', [ __CLASS__, 'maybe_wrap_flipbook' ] );

        // Inject Open Graph / Twitter Card meta tags for sharing
        add_action( 'wp_head', [ __CLASS__, 'maybe_output_og_tags' ] );
    }

    // ── Frontend hooks ────────────────────────────────────────────────────

    public static function maybe_enqueue_flipbook(): void {
        if ( ! is_singular( 'post' ) ) {
            return;
        }
        if ( ! get_post_meta( get_the_ID(), 'sas_content_type', true ) ) {
            return;
        }

        wp_enqueue_style(
            'sas-flipbook',
            SAS_PLUGIN_URL . 'public/css/sas-flipbook.css',
            [],
            SAS_VERSION
        );

        wp_enqueue_script(
            'page-flip',
            SAS_PLUGIN_URL . 'public/js/vendor/page-flip.browser.min.js',
            [],
            '2.0.7',
            true
        );

        wp_enqueue_script(
            'sas-flipbook',
            SAS_PLUGIN_URL . 'public/js/sas-flipbook.js',
            [ 'page-flip' ],
            SAS_VERSION,
            true
        );
    }

    public static function maybe_wrap_flipbook( string $content ): string {
        if ( ! is_singular( 'post' ) || ! in_the_loop() ) {
            return $content;
        }
        if ( ! get_post_meta( get_the_ID(), 'sas_content_type', true ) ) {
            return $content;
        }

        $nav = '<div class="sas-flipbook-nav" aria-label="Flipbook navigation">
            <button id="sas-flip-prev" class="sas-flip-btn">&#9664; Previous</button>
            <span id="sas-flip-counter" class="sas-flip-counter"></span>
            <button id="sas-flip-next" class="sas-flip-btn">Next &#9654;</button>
        </div>';

        $share = '<div class="sas-share-bar">
            <span class="sas-share-label">&#128279; Share:</span>
            <button class="sas-share-btn" data-network="whatsapp">&#128242; WhatsApp</button>
            <button class="sas-share-btn" data-network="facebook">&#128101; Facebook</button>
            <button class="sas-share-btn" data-network="copy">&#128203; Copy Link</button>
        </div>';

        return '<div class="sas-flipbook-wrap">'
             .   '<div class="sas-flipbook-container">'
             .     $content
             .   '</div>'
             . '</div>'
             . $nav
             . $share;
    }

    public static function maybe_output_og_tags(): void {
        if ( ! is_singular( 'post' ) ) {
            return;
        }
        $post_id = get_the_ID();
        if ( ! get_post_meta( $post_id, 'sas_content_type', true ) ) {
            return;
        }

        $title   = get_the_title( $post_id );
        $excerpt = wp_strip_all_tags( get_the_excerpt( $post_id ) );
        $url     = get_permalink( $post_id );
        $image   = get_the_post_thumbnail_url( $post_id, 'large' ) ?: '';

        echo '<meta property="og:type" content="article">' . "\n";
        echo '<meta property="og:title" content="' . esc_attr( $title ) . '">' . "\n";
        echo '<meta property="og:description" content="' . esc_attr( $excerpt ) . '">' . "\n";
        echo '<meta property="og:url" content="' . esc_url( $url ) . '">' . "\n";
        if ( $image ) {
            echo '<meta property="og:image" content="' . esc_url( $image ) . '">' . "\n";
        }
        echo '<meta name="twitter:card" content="summary_large_image">' . "\n";
        echo '<meta name="twitter:title" content="' . esc_attr( $title ) . '">' . "\n";
        echo '<meta name="twitter:description" content="' . esc_attr( $excerpt ) . '">' . "\n";
        if ( $image ) {
            echo '<meta name="twitter:image" content="' . esc_url( $image ) . '">' . "\n";
        }
    }

    // ── Category setup ────────────────────────────────────────────────────

    /**
     * Create the three top-level categories + their subcategories.
     *
     * @return array { created: int, existing: int }
     */
    public static function setup_categories(): array {
        $created  = 0;
        $existing = 0;

        // ── Hindu Calendar ─────────────────────────────────────────────────
        $cal_id = self::ensure_category( 'Hindu Calendar' );
        if ( $cal_id === 0 ) {
            $existing++;
        } else {
            $created++;
        }
        $cal_root = get_term_by( 'name', 'Hindu Calendar', 'category' );
        $cal_parent = $cal_root ? (int) $cal_root->term_id : 0;

        foreach ( array_keys( self::COUNTRIES ) as $country ) {
            $id = self::ensure_category( 'Hindu Calendar ' . $country, $cal_parent );
            $id === 0 ? $existing++ : $created++;
        }

        // ── Pooja Guides ───────────────────────────────────────────────────
        $id = self::ensure_category( 'Pooja Guides' );
        $id === 0 ? $existing++ : $created++;
        $pooja_root = get_term_by( 'name', 'Pooja Guides', 'category' );
        $pooja_parent = $pooja_root ? (int) $pooja_root->term_id : 0;

        // Create subcategory per deity name (derived from pooja names)
        $deities_added = [];
        foreach ( self::POOJAS as $pooja ) {
            $deity = self::pooja_to_deity( $pooja );
            if ( ! isset( $deities_added[ $deity ] ) ) {
                $id = self::ensure_category( $deity . ' Puja', $pooja_parent );
                $id === 0 ? $existing++ : $created++;
                $deities_added[ $deity ] = true;
            }
        }

        // ── Slokas & Mantras ───────────────────────────────────────────────
        $id = self::ensure_category( 'Slokas & Mantras' );
        $id === 0 ? $existing++ : $created++;
        $sloka_root = get_term_by( 'name', 'Slokas & Mantras', 'category' );
        $sloka_parent = $sloka_root ? (int) $sloka_root->term_id : 0;

        foreach ( self::SLOKA_DEITIES as $deity ) {
            $id = self::ensure_category( $deity . ' Slokas', $sloka_parent );
            $id === 0 ? $existing++ : $created++;
        }

        return [ 'created' => $created, 'existing' => $existing ];
    }

    // ── Post generators ───────────────────────────────────────────────────

    /**
     * Generate a single Hindu Calendar post.
     */
    public static function generate_calendar_post( int $year, string $month, string $country, string $lang ): array {
        $lang_name = self::LANG_NAMES[ $lang ] ?? 'English';
        $timezone  = self::COUNTRIES[ $country ] ?? 'UTC';
        $country_slug = sanitize_title( $country );
        $month_slug   = sanitize_title( $month );
        $slug = "hindu-calendar-{$year}-{$month_slug}-{$country_slug}-{$lang}";

        if ( self::post_exists( $slug ) ) {
            return [ 'status' => 'skipped', 'slug' => $slug ];
        }

        $title   = "Hindu Calendar {$year} — {$month} | {$country} | " . $lang_name;
        $content = self::gemini_text( self::calendar_prompt( $year, $month, $country, $timezone, $lang_name ) );

        if ( ! $content ) {
            return [ 'status' => 'error', 'error' => 'Gemini returned empty content.' ];
        }

        // Category: Hindu Calendar {Country}
        $cat_name = "Hindu Calendar {$country}";
        $cat_term = get_term_by( 'name', $cat_name, 'category' );
        $cats     = $cat_term ? [ (int) $cat_term->term_id ] : [];

        $post_id = self::make_post( [
            'post_title'   => $title,
            'post_content' => $content,
            'post_name'    => $slug,
            'categories'   => $cats,
            'tags'         => [ (string) $year, $month, $country, $lang_name, 'Hindu Calendar', 'Panchang' ],
            'meta'         => [
                'sas_content_type' => self::TYPE_CALENDAR,
                'sas_language'     => $lang,
                'sas_country'      => $country,
                'sas_year'         => (string) $year,
                'sas_month'        => $month,
            ],
        ] );

        if ( is_wp_error( $post_id ) ) {
            return [ 'status' => 'error', 'error' => $post_id->get_error_message() ];
        }

        return [ 'status' => 'created', 'post_id' => $post_id, 'title' => $title ];
    }

    /**
     * Generate a single Pooja Guide post.
     */
    public static function generate_pooja_post( string $pooja, string $lang ): array {
        $lang_name  = self::LANG_NAMES[ $lang ] ?? 'English';
        $pooja_slug = sanitize_title( $pooja );
        $slug       = "{$pooja_slug}-guide-{$lang}";

        if ( self::post_exists( $slug ) ) {
            return [ 'status' => 'skipped', 'slug' => $slug ];
        }

        $title   = $pooja . ' — Step by Step Guide | ' . $lang_name;
        $content = self::gemini_text( self::pooja_prompt( $pooja, $lang_name ) );

        if ( ! $content ) {
            return [ 'status' => 'error', 'error' => 'Gemini returned empty content.' ];
        }

        $deity    = self::pooja_to_deity( $pooja );
        $cat_name = $deity . ' Puja';
        $cat_term = get_term_by( 'name', $cat_name, 'category' );
        $pooja_parent = get_term_by( 'name', 'Pooja Guides', 'category' );
        $cats = [];
        if ( $cat_term ) {
            $cats[] = (int) $cat_term->term_id;
        } elseif ( $pooja_parent ) {
            $cats[] = (int) $pooja_parent->term_id;
        }

        $post_id = self::make_post( [
            'post_title'   => $title,
            'post_content' => $content,
            'post_name'    => $slug,
            'categories'   => $cats,
            'tags'         => [ $deity, $lang_name, 'Pooja', 'Puja Guide', 'Step by Step', 'Mantra' ],
            'meta'         => [
                'sas_content_type' => self::TYPE_POOJA,
                'sas_language'     => $lang,
                'sas_pooja'        => $pooja,
            ],
        ] );

        if ( is_wp_error( $post_id ) ) {
            return [ 'status' => 'error', 'error' => $post_id->get_error_message() ];
        }

        return [ 'status' => 'created', 'post_id' => $post_id, 'title' => $title ];
    }

    /**
     * Generate a single Sloka Collection post.
     */
    public static function generate_sloka_post( string $deity, string $lang ): array {
        $lang_name   = self::LANG_NAMES[ $lang ] ?? 'English';
        $deity_slug  = sanitize_title( $deity );
        $slug        = "{$deity_slug}-slokas-{$lang}";

        if ( self::post_exists( $slug ) ) {
            return [ 'status' => 'skipped', 'slug' => $slug ];
        }

        $title   = $deity . ' Slokas & Mantras | ' . $lang_name;
        $content = self::gemini_text( self::sloka_prompt( $deity, $lang_name ) );

        if ( ! $content ) {
            return [ 'status' => 'error', 'error' => 'Gemini returned empty content.' ];
        }

        $cat_name = $deity . ' Slokas';
        $cat_term = get_term_by( 'name', $cat_name, 'category' );
        $sloka_parent = get_term_by( 'name', 'Slokas & Mantras', 'category' );
        $cats = [];
        if ( $cat_term ) {
            $cats[] = (int) $cat_term->term_id;
        } elseif ( $sloka_parent ) {
            $cats[] = (int) $sloka_parent->term_id;
        }

        $post_id = self::make_post( [
            'post_title'   => $title,
            'post_content' => $content,
            'post_name'    => $slug,
            'categories'   => $cats,
            'tags'         => [ $deity, $lang_name, 'Sloka', 'Mantra', 'Sanskrit', 'Devotion' ],
            'meta'         => [
                'sas_content_type' => self::TYPE_SLOKA,
                'sas_language'     => $lang,
                'sas_deity'        => $deity,
            ],
        ] );

        if ( is_wp_error( $post_id ) ) {
            return [ 'status' => 'error', 'error' => $post_id->get_error_message() ];
        }

        return [ 'status' => 'created', 'post_id' => $post_id, 'title' => $title ];
    }

    /**
     * Generate and assign a featured image for a content engine post.
     *
     * @param int    $post_id    WP post ID
     * @param string $type       TYPE_CALENDAR / TYPE_POOJA / TYPE_SLOKA
     * @param string $subject    e.g. "Ganesh Puja" or "Ganesha" or "January 2026 India"
     * @return bool
     */
    public static function generate_image_for_post( int $post_id, string $type, string $subject ): bool {
        $api_key = sas_get_settings()['gemini_api_key'] ?? '';
        if ( ! $api_key ) {
            return false;
        }

        // Don't regenerate if already has thumbnail
        if ( has_post_thumbnail( $post_id ) ) {
            return false;
        }

        $prompt = match ( $type ) {
            self::TYPE_CALENDAR => "Sacred Hindu festival calendar illustration for {$subject} — vibrant saffron and gold tones, traditional Indian art style, flowers, diyas, rangoli, no text, no watermark",
            self::TYPE_POOJA    => "Beautiful Hindu puja scene for {$subject} — deity idol on decorated altar, flowers, incense, diyas, warm golden light, devotional aesthetic, no text",
            self::TYPE_SLOKA    => "Serene spiritual illustration of {$subject} — intricate mandala motifs, saffron and lotus, divine light, sacred Sanskrit energy, devotional art style, no text",
            default             => "Sacred Hindu spiritual illustration — saffron and gold tones, divine aesthetic, no text",
        };

        require_once ABSPATH . 'wp-admin/includes/image.php';
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';

        $endpoint = 'https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-fast-generate-001:predict?key=' . rawurlencode( $api_key );

        $response = wp_remote_post( $endpoint, [
            'timeout' => 60,
            'headers' => [ 'Content-Type' => 'application/json' ],
            'body'    => wp_json_encode( [
                'instances'  => [ [ 'prompt' => $prompt ] ],
                'parameters' => [ 'sampleCount' => 1 ],
            ] ),
        ] );

        if ( is_wp_error( $response ) ) {
            return false;
        }

        $body = json_decode( wp_remote_retrieve_body( $response ), true );
        $b64  = $body['predictions'][0]['bytesBase64Encoded'] ?? '';
        $mime = $body['predictions'][0]['mimeType'] ?? 'image/png';
        $ext  = ( $mime === 'image/jpeg' ) ? 'jpg' : 'png';

        if ( ! $b64 ) {
            return false;
        }

        $filename = 'sas-content-' . $post_id . '.' . $ext;
        $upload   = wp_upload_bits( $filename, null, base64_decode( $b64 ) );

        if ( ! empty( $upload['error'] ) ) {
            return false;
        }

        $attachment_id = wp_insert_attachment( [
            'post_mime_type' => $mime,
            'post_title'     => sanitize_file_name( get_the_title( $post_id ) ),
            'post_content'   => '',
            'post_status'    => 'inherit',
        ], $upload['file'], $post_id );

        if ( is_wp_error( $attachment_id ) ) {
            return false;
        }

        $attach_data = wp_generate_attachment_metadata( $attachment_id, $upload['file'] );
        wp_update_attachment_metadata( $attachment_id, $attach_data );
        set_post_thumbnail( $post_id, $attachment_id );

        return true;
    }

    // ── Gemini text generation ────────────────────────────────────────────

    private static function gemini_text( string $prompt ): string {
        $api_key = sas_get_settings()['gemini_api_key'] ?? '';
        if ( ! $api_key ) {
            return '';
        }

        $response = wp_remote_post(
            'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=' . rawurlencode( $api_key ),
            [
                'timeout' => 60,
                'headers' => [ 'Content-Type' => 'application/json' ],
                'body'    => wp_json_encode( [
                    'contents' => [ [ 'parts' => [ [ 'text' => $prompt ] ] ] ],
                    'generationConfig' => [
                        'maxOutputTokens' => 8192,
                        'temperature'     => 0.7,
                    ],
                ] ),
            ]
        );

        if ( is_wp_error( $response ) ) {
            return '';
        }

        $body = json_decode( wp_remote_retrieve_body( $response ), true );
        $html = $body['candidates'][0]['content']['parts'][0]['text'] ?? '';

        // Strip any accidental markdown code fences
        $html = preg_replace( '/^```html?\s*/i', '', trim( $html ) );
        $html = preg_replace( '/\s*```$/i', '', $html );

        return wp_kses_post( trim( $html ) );
    }

    // ── Prompt templates ──────────────────────────────────────────────────

    private static function calendar_prompt( int $year, string $month, string $country, string $timezone, string $lang_name ): string {
        return <<<PROMPT
Write a comprehensive Hindu calendar guide for {$month} {$year} for Hindu devotees in {$country} ({$timezone} timezone).
ALL explanatory content should be in {$lang_name} language. Keep Sanskrit festival names in their original form but explain them in {$lang_name}.

Structure the response as ONLY pure HTML using these exact div sections (no markdown, no code fences, no DOCTYPE):

<div class="sas-flip-page sas-page-cover">
<h1>{$month} {$year} Hindu Calendar — {$country}</h1>
<p>[Month overview in {$lang_name}: spiritual theme, which deities are honoured, seasonal significance for Hindu families in {$country}. 3 sentences.]</p>
</div>

<div class="sas-flip-page">
<h2>Major Festivals &amp; Celebrations</h2>
[List each major festival this month as <div class="sas-festival-item"><h3>Festival Name</h3><p><strong>Date:</strong> [date adjusted for {$timezone}]</p><p>[2-sentence description in {$lang_name}. Traditional practices. Why it's celebrated.]</p></div>]
</div>

<div class="sas-flip-page">
<h2>Ekadashi, Purnima &amp; Amavasya</h2>
[For each: date in {$timezone}, name, significance in {$lang_name}, recommended fast/pooja. Format as a structured list.]
</div>

<div class="sas-flip-page">
<h2>Auspicious Days &amp; Muhurat</h2>
<p>[Explain auspicious days this month for weddings, griha pravesh, new ventures, travel — for families in {$country}. In {$lang_name}.]</p>
</div>

<div class="sas-flip-page">
<h2>Monthly Sloka &amp; Blessing</h2>
<blockquote class="sas-mantra">[Most relevant Sanskrit sloka for this month's main festival — in Devanagari]</blockquote>
<p class="sas-transliteration">[IAST transliteration]</p>
<p class="sas-mantra-meaning">[{$lang_name} translation and meaning]</p>
<p>[Who to recite to, best time of day, number of repetitions. In {$lang_name}.]</p>
</div>

Return ONLY the 5 div blocks above. No extra wrapper tags. No markdown.
PROMPT;
    }

    private static function pooja_prompt( string $pooja, string $lang_name ): string {
        return <<<PROMPT
Write a complete, devotionally authentic step-by-step guide for performing {$pooja}.
ALL explanatory text in {$lang_name}. Sanskrit mantras in original Devanagari script with {$lang_name} translation.

Structure as ONLY pure HTML using these exact div sections (no markdown, no code fences, no DOCTYPE):

<div class="sas-flip-page sas-page-cover">
<h1>{$pooja}</h1>
<p>[Significance: which deity, spiritual benefit, why Hindus perform this puja. Best day and time. 3 sentences in {$lang_name}.]</p>
</div>

<div class="sas-flip-page">
<h2>Samagri (Puja Materials)</h2>
<ul>[Each item as <li><strong>Item name</strong> — brief explanation of its significance in {$lang_name}]</li>. List 10-15 items.]</ul>
</div>

[For each step (create 6 to 8 steps):]
<div class="sas-flip-page">
<h2>Step [N]: [Step title in {$lang_name}]</h2>
<p>[Detailed instruction in {$lang_name}. What to do, how to do it, the spiritual intention.]</p>
<blockquote class="sas-mantra">[Sanskrit mantra for this step in Devanagari — most commonly used]</blockquote>
<p class="sas-mantra-meaning">[{$lang_name} meaning of the mantra]</p>
</div>

<div class="sas-flip-page">
<h2>Aarti &amp; Closing Prayer</h2>
<p>[Aarti instructions in {$lang_name}. Which aarti to sing. How to conclude the puja.]</p>
<p class="sas-benefit">[Phala Shruti: spiritual benefits of performing this puja. In {$lang_name}.]</p>
</div>

Return ONLY the div blocks. No markdown. No extra tags.
PROMPT;
    }

    private static function sloka_prompt( string $deity, string $lang_name ): string {
        return <<<PROMPT
Compile the 12 most important and widely-chanted {$deity} slokas/mantras/stotrams for Hindu devotees.
Explanatory text in {$lang_name}. Sanskrit slokas in Devanagari script.

Structure as ONLY pure HTML using these exact div sections (no markdown, no code fences, no DOCTYPE):

<div class="sas-flip-page sas-page-cover">
<h1>{$deity} Slokas &amp; Mantras</h1>
<p>[Introduction: who is {$deity}, spiritual significance, benefits of chanting these slokas, best time to chant. 3-4 sentences in {$lang_name}.]</p>
</div>

[For each of the 12 slokas:]
<div class="sas-flip-page">
<h2>[N]. [Sloka Name in {$lang_name}]</h2>
<blockquote class="sas-mantra">[Sanskrit text in Devanagari — full sloka]</blockquote>
<p class="sas-transliteration">[IAST transliteration]</p>
<p class="sas-meaning"><strong>[{$lang_name} Translation:]</strong> [full meaning in {$lang_name}]</p>
<p class="sas-benefit">[Spiritual benefit and recommended number of repetitions (jaap). In {$lang_name}.]</p>
</div>

<div class="sas-flip-page">
<h2>Phala Shruti</h2>
<p>[Benefits of reading this complete collection. Best time and day. Dedication. In {$lang_name}.]</p>
<blockquote class="sas-mantra">[A closing/dedication verse in Sanskrit Devanagari]</blockquote>
<p class="sas-mantra-meaning">[{$lang_name} meaning]</p>
</div>

Return ONLY the div blocks. No markdown. No extra tags.
PROMPT;
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    /**
     * Check if a post with the given slug already exists.
     */
    private static function post_exists( string $slug ): bool {
        $post = get_page_by_path( $slug, OBJECT, 'post' );
        return $post !== null;
    }

    /**
     * Get or create a WordPress category. Returns term_id, or 0 if it already existed.
     */
    private static function ensure_category( string $name, int $parent = 0 ): int {
        $existing = get_term_by( 'name', $name, 'category' );
        if ( $existing && ! is_wp_error( $existing ) ) {
            // Check it has the right parent
            if ( $parent === 0 || (int) $existing->parent === $parent ) {
                return 0; // Already exists
            }
        }

        $result = wp_insert_term( $name, 'category', [ 'parent' => $parent ] );
        if ( is_wp_error( $result ) ) {
            // May have been created by a concurrent request — treat as existing
            $existing = get_term_by( 'name', $name, 'category' );
            return ( $existing && ! is_wp_error( $existing ) ) ? (int) $existing->term_id : 0;
        }

        return (int) $result['term_id'];
    }

    /**
     * Create a WordPress post with categories, tags, and meta.
     */
    private static function make_post( array $args ): int|WP_Error {
        $post_id = wp_insert_post( [
            'post_type'    => 'post',
            'post_status'  => 'publish',
            'post_title'   => $args['post_title'],
            'post_content' => $args['post_content'],
            'post_name'    => $args['post_name'],
            'post_excerpt' => wp_trim_words( wp_strip_all_tags( $args['post_content'] ), 30, '...' ),
        ], true );

        if ( is_wp_error( $post_id ) ) {
            return $post_id;
        }

        // Assign categories
        if ( ! empty( $args['categories'] ) ) {
            wp_set_post_categories( $post_id, $args['categories'] );
        }

        // Assign tags
        if ( ! empty( $args['tags'] ) ) {
            wp_set_post_tags( $post_id, $args['tags'], false );
        }

        // Store post meta
        if ( ! empty( $args['meta'] ) ) {
            foreach ( $args['meta'] as $key => $value ) {
                update_post_meta( $post_id, $key, $value );
            }
        }

        return $post_id;
    }

    /**
     * Extract the deity/primary subject from a pooja name.
     * e.g. "Ganesh Puja" → "Ganesh", "Diwali Lakshmi Puja" → "Lakshmi"
     */
    private static function pooja_to_deity( string $pooja ): string {
        $map = [
            'Ganesh Puja'             => 'Ganesh',
            'Lakshmi Puja'            => 'Lakshmi',
            'Saraswati Puja'          => 'Saraswati',
            'Shiva Puja'              => 'Shiva',
            'Durga Puja'              => 'Durga',
            'Hanuman Puja'            => 'Hanuman',
            'Satyanarayan Puja'       => 'Vishnu',
            'Navgraha Puja'           => 'Navgraha',
            'Kali Puja'               => 'Kali',
            'Krishna Janmashtami Puja'=> 'Krishna',
            'Ram Navami Puja'         => 'Rama',
            'Navratri Puja'           => 'Durga',
            'Diwali Lakshmi Puja'     => 'Lakshmi',
            'Holika Dahan Puja'       => 'Vishnu',
            'Chhath Puja'             => 'Surya',
            'Karva Chauth Puja'       => 'Shiva',
            'Vastu Puja'              => 'Vastu',
            'Griha Pravesh Puja'      => 'Vastu',
            'Vivah Puja'              => 'Agni',
            'Annaprashan Puja'        => 'Vishnu',
        ];
        return $map[ $pooja ] ?? 'Hindu';
    }

    // ── Public data accessors (for admin UI batch building) ───────────────

    public static function get_all_calendar_items( int $year = 2026 ): array {
        $items = [];
        foreach ( self::MONTHS as $month ) {
            foreach ( array_keys( self::COUNTRIES ) as $country ) {
                foreach ( array_keys( self::LANG_NAMES ) as $lang ) {
                    $items[] = [
                        'year'    => $year,
                        'month'   => $month,
                        'country' => $country,
                        'lang'    => $lang,
                    ];
                }
            }
        }
        return $items; // 324 items
    }

    public static function get_all_pooja_items(): array {
        $items = [];
        foreach ( self::POOJAS as $pooja ) {
            foreach ( array_keys( self::LANG_NAMES ) as $lang ) {
                $items[] = [ 'pooja' => $pooja, 'lang' => $lang ];
            }
        }
        return $items; // 180 items
    }

    public static function get_all_sloka_items(): array {
        $items = [];
        foreach ( self::SLOKA_DEITIES as $deity ) {
            foreach ( array_keys( self::LANG_NAMES ) as $lang ) {
                $items[] = [ 'deity' => $deity, 'lang' => $lang ];
            }
        }
        return $items; // 90 items
    }

    /**
     * Return counts of already-generated posts per type.
     */
    public static function get_counts(): array {
        $meta_query = [ 'meta_key' => 'sas_content_type' ];

        $cal = get_posts( array_merge( [ 'post_type' => 'post', 'posts_per_page' => -1,
            'fields' => 'ids', 'meta_query' => [
                [ 'key' => 'sas_content_type', 'value' => self::TYPE_CALENDAR ],
            ] ], [] ) );

        $pooja = get_posts( [ 'post_type' => 'post', 'posts_per_page' => -1,
            'fields' => 'ids', 'meta_query' => [
                [ 'key' => 'sas_content_type', 'value' => self::TYPE_POOJA ],
            ] ] );

        $sloka = get_posts( [ 'post_type' => 'post', 'posts_per_page' => -1,
            'fields' => 'ids', 'meta_query' => [
                [ 'key' => 'sas_content_type', 'value' => self::TYPE_SLOKA ],
            ] ] );

        return [
            'calendar' => count( $cal ),
            'pooja'    => count( $pooja ),
            'sloka'    => count( $sloka ),
        ];
    }
}
